"""initial

Revision ID: 083b2d8c4255
Revises:
Create Date: 2026-05-14 20:20:17.860572

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "083b2d8c4255"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scenario",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column("start_season", sa.String(length=10), nullable=False),
        sa.Column("end_season", sa.String(length=10), nullable=False),
        sa.Column("locked", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scenario_id", sa.Integer(), nullable=True),
        sa.Column(
            "ts", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("entity", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "base_table_row",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scenario_id", sa.Integer(), nullable=False),
        sa.Column("project_name", sa.String(length=200), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("total", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "new_project_group",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scenario_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scenario_id", sa.Integer(), nullable=False),
        sa.Column("royaltie_fob", sa.Float(), nullable=False),
        sa.Column("costo_plantines", sa.Float(), nullable=False),
        sa.Column("interes_financiamiento", sa.Float(), nullable=False),
        sa.Column("financiamiento_anios", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scenario_id"),
    )
    op.create_table(
        "season",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scenario_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "variety",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scenario_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "base_table_value",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("base_table_row_id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["base_table_row_id"],
            ["base_table_row.id"],
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["season.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "base_table_variation",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scenario_id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scenario_id"],
            ["scenario.id"],
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["season.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "new_project_subrow",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("variety_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["new_project_group.id"],
        ),
        sa.ForeignKeyConstraint(
            ["variety_id"],
            ["variety.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "variety_param",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("variety_id", sa.Integer(), nullable=False),
        sa.Column("plant_year", sa.Integer(), nullable=False),
        sa.Column("productividad", sa.Float(), nullable=False),
        sa.Column("densidad", sa.Float(), nullable=False),
        sa.Column("precio_estimado", sa.Float(), nullable=False),
        sa.Column("pct_recaudacion", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["variety_id"],
            ["variety.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("variety_id", "plant_year", name="uq_variety_plant_year"),
    )
    op.create_table(
        "new_project_ha",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("subrow_id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("hectareas", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["season.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subrow_id"],
            ["new_project_subrow.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subrow_id", "season_id", name="uq_subrow_season"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("new_project_ha")
    op.drop_table("variety_param")
    op.drop_table("new_project_subrow")
    op.drop_table("base_table_variation")
    op.drop_table("base_table_value")
    op.drop_table("variety")
    op.drop_table("season")
    op.drop_table("rules")
    op.drop_table("new_project_group")
    op.drop_table("base_table_row")
    op.drop_table("audit_log")
    op.drop_table("scenario")
    # ### end Alembic commands ###
